receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ""
      "x-honeycomb-dataset": "ObservableLambdaDemoTraces"
  otlp/logs:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ""
      "x-honeycomb-dataset": "ObservableLambdaDemoLogs"
  otlp/metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ""
      "x-honeycomb-dataset": "ObservableLambdaDemoLogs"
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
    logs:
      receivers: [ otlp ]
      exporters: [ otlp/logs ]