receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "ObservableLambdaDemoTraces"
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]