AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for dotnet-lambda-observability

Globals:
  Function:
    Timeout: 10
    Tracing: PassThrough
    MemorySize: 512
    Environment:
      Variables:
        OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/config.yaml
  Api:
    TracingEnabled: True

Resources:
  ObservableLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ObservableLambda/
      Handler: ObservableLambda::ObservableLambda.Function::TracedFunctionHandler
      Layers:
        - arn:aws:lambda:eu-west-1:901920570463:layer:aws-otel-collector-amd64-ver-0-61-0:1
      Runtime: dotnet6
      Architectures:
        - x86_64
      Environment:
        Variables:
          TOPIC_ARN: !Ref PublishTopic
      Policies:
      - SNSPublishMessagePolicy:
          TopicName: "otel-test-publish-topic"
      Events:
        ApiEndpoint:
          Type: Api
          Properties:
            Path: /observe-me
            Method: get
            
  PublishTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "otel-test-publish-topic"

Outputs:
  ObservableLambdaApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/observe-me/"
