name: NET 6

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/OTEL/**
jobs:

  build-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2  
        - name: Build and Deploy
          uses: ./.github/actions/sam-build-and-deploy
          with:
            aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
            dotnet-version: '6.0.x'
            template-file-path: ./src/OTEL/template.yaml
            stack-name: observable-lambda-otel-demo
            s3-bucket-name: aws-sam-cli-managed-default-samclisourcebucket-1bb5unt6m9r3a
            honeycomb-api-key: ${{secrets.HONEYCOMB_API_KEY}}